### ISSUE TITLE
The EcsRamRoleSigner may cause request storm to ecs metaserver

### ISSUE THREAD

**Issue by mozillazg** [aliyun/alibaba-cloud-sdk-go#397] opened 2020-03-11 07:51 UTC
The EcsRamRoleSigner will check and/or refresh sts token on every request, this way may cause request storm to ecs metaserver when the program which use this sdk is running under high concurrency scene. 

ecs metaserver will limit requests from sdk in this case that will cause request timeout or got error like `refresh Ecs sts token err: Get http://100.100.100.200/latest/meta-data/ram/security-credentials/xxx: EOF`

How about export the `Client.signer` ? Use this way to allow users to refresh sts token via a background job to prevent sdk from DDoS ecs metaserver under high concurrency scene.

Or maybe we should change the way to check and refresh sts token, use a background job instead of check on every request.

Or maybe we should add a lock when refresh sts token?

**Comment by wenzuochao** [comment] 2020-03-11 09:45
Every client has own signer， if you use different client, the signer is different.

**Comment by mozillazg** [comment] 2020-03-11 10:01
@wenzuochao You mean i should create new client for every incoming request or every goroutine when i use this sdk in a service program?

**Comment by mozillazg** [comment] 2020-03-11 10:11
Even though i create new client for every requests/goroutines this issue is still exist.

**Comment by wenzuochao** [comment] 2020-03-11 10:15
I mean  every client has own signer , the problem is appearred when too many clients call api by using  the same ecs role.

**Comment by mozillazg** [comment] 2020-03-11 10:59
But as a service program use only one ecs role to serve all incoming requests is a normal case.

**Comment by wenzuochao** [comment] 2020-03-11 11:27
I know what you say, but it's hard to repair,  we will fix it in next major version.

**Comment by mozillazg** [comment] 2020-03-12 04:01
👌

**Comment by wenzuochao** [comment] 2020-03-12 09:11
The pull request is merged, you can use one signer for all clients. But you should avoid date race by your self.

**Comment by mozillazg** [comment] 2020-03-12 09:31
@wenzuochao 👌

**Closed** 2020-03-12 09:32 UTC
